#!/bin/bash

cf set-env $APP_NAME EASEY_AUTH_API_KEY $AUTH_API_API_KEY
cf set-env $APP_NAME EASEY_AUTH_API_SECRET_TOKEN $AUTH_API_SECRET_TOKEN
cf set-env $APP_NAME OIDC_CLIENT_SECRET $AUTH_API_OIDC_CLIENT_SECRET
cf set-env $APP_NAME OIDC_HMAC_SECRET_KEY $AUTH_API_OIDC_HMAC_SECRET_KEY
