#!/bin/bash

cf set-env $APP_NAME EASEY_CDX_BYPASS_PASSWORD $CDX_BYPASS_PASSWORD
cf set-env $APP_NAME EASEY_NAAS_SERVICES_APP_ID $NAAS_SERVICES_APP_ID
cf set-env $APP_NAME EASEY_NAAS_SERVICES_APP_PASSWORD $NAAS_SERVICES_APP_PASSWORD
cf set-env $APP_NAME EASEY_AUTH_API_SECRET_TOKEN $AUTH_API_SECRET_TOKEN
